---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, Volume caching 
summary: Durch Volume-Caching wird ein dauerhaftes, beschreibbares Volume an einem entfernten Ort bereitgestellt.  Sie können Volume-Caching verwenden, um den Zugriff auf Daten zu beschleunigen oder den Datenverkehr von stark beanspruchten Volumes zu entlasten.  Cache-Volumes eignen sich ideal für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen. 
---
= Verwalten eines Caches
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Cache bearbeiten, die Exportrichtlinie ändern, die Größe eines Caches ändern und einen Cache löschen.

Mit Volume-Caching können Sie folgende Ziele erreichen:

* Cachedetails anzeigen.
* Weisen Sie einem Cache eine andere Exportrichtlinie zu.
* Bearbeiten Sie ein Volume-Caching und ändern Sie seine Größe usw. Beim Bearbeiten besteht die Möglichkeit, andere Eigenschaften anzuzeigen und zu ändern. In zukünftigen Versionen werden beim Bearbeiten weitere Eigenschaften hinzugefügt.
* Ändern Sie die Größe eines vorhandenen Cache basierend auf einem Prozentsatz der ursprünglichen Volumegröße.
* Löschen Sie einen Cache.




== Cachedetails anzeigen

Für jeden Cache können Sie das ursprüngliche Volume, die Arbeitsumgebung, das Cache-Volume und mehr sehen.

.Schritte
. Wählen Sie in der linken Navigation der NetApp Konsole *Mobilität* > *Volume-Caching*.
+
Sie können die Liste der auf dem Zielsystem erstellten Cache-Volumes anzeigen.  Die Cacheliste zeigt die Cachedetails an.

. Um die Liste zu filtern, wählen Sie die Option *Filtern nach +*.
. Wählen Sie eine Zeile aus und wählen Sie rechts die Option *Aktionen …*.
. Wählen Sie *Details anzeigen und bearbeiten*.
. Überprüfen Sie die Details.




== Einen Cache bearbeiten

Sie können den Namen, die Volumegröße und die Exportrichtlinie für einen Cache ändern.

.Schritte
. Wählen Sie in der linken Navigation der NetApp Konsole *Mobilität* > *Volume-Caching*.
. Wählen Sie eine Zeile aus und wählen Sie rechts die Option *Aktionen …*.
. Wählen Sie *Details anzeigen und bearbeiten*.
. Ändern Sie auf der Registerkarte „Grundkonfiguration“ optional den Cachenamen und die Cachevolumegröße.
. Erweitern Sie optional die Registerkarte Cache-Zugriff und ändern Sie diese Werte:
+
.. Der Mount-Pfad.
.. Eine Exportrichtlinie, die sich von der bestehenden unterscheidet.


. Um SMB/CIFS-Freigabedetails oder die Exportrichtlinienregeln zu ändern, klicken Sie auf die Option zum Zugriff auf NetApp System Manager.
. Wählen Sie *Speichern*.




== Zuweisen einer anderen Cache-Exportrichtlinie

Sie können einem Cache eine andere Exportrichtlinie zuweisen.

Die Regeln der Quellexportrichtlinie sollten auf den Zielcluster angewendet werden.


TIP: Sie können einem Cache eine vorhandene Exportrichtlinie zuweisen.  Sie können die Exportrichtlinienregeln nicht ändern.  Wenn Sie die Exportrichtlinien ändern müssen, können Sie NetApp System Manager verwenden.

.Schritte
. Wählen Sie in der linken Navigation der NetApp Konsole *Mobilität* > *Volume-Caching*.
. Wählen Sie eine Zeile aus und wählen Sie rechts die Option *Aktionen …*.
. Wählen Sie *Exportrichtlinie ändern*.
. Wählen Sie die Exportrichtlinie aus, die Sie dem Cache zuweisen möchten.
. Wählen Sie *Speichern*.




== Ändern der Cachegröße

Sie können die Größe des Cache-Volumes basierend auf einem Prozentsatz des Quellvolumes ändern.

.Schritte
. Wählen Sie in der linken Navigation der NetApp Konsole *Mobilität* > *Volume-Caching*.
. Wählen Sie eine Zeile aus und wählen Sie rechts die Option *Aktionen …*.
. Wählen Sie *Größe ändern*.
. Geben Sie einen neuen Prozentsatz der ursprünglichen Volumengröße ein.
+
Die Größe des Cache-Volumens wird auf den neuen Prozentsatz angepasst.

. Wählen Sie *Speichern*.




== Löschen eines Caches

Wenn Sie den Cache nicht mehr benötigen, können Sie ihn löschen.  Dadurch wird die Volume-Caching-Beziehung gelöscht und der Zielvolume-Cache gelöscht.

.Schritte
. Wählen Sie in der linken Navigation der NetApp Konsole *Mobilität* > *Volume-Caching*.
. Wählen Sie eine Zeile aus und wählen Sie rechts die Option *Aktionen …*.
. Wählen Sie *Löschen*.
. Aktivieren Sie das Kontrollkästchen.
. Wählen Sie *Löschen*.

